### ISSUE TITLE
Bug in Derivative

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/PiecewiseOrthogonalPolynomials.jl#15]
@dlfivefifty I think there is a bug in `Derivative(x) * ContinuousPolynomial{1}(r)`. E.g.

```
n = 5; r = range(0, 1; length=n+1) # solve on unit interval with n cells

C¹ = ContinuousPolynomial{1}(r) # hat functions and (1-x^2) * P_k^(1,1)(x)
C⁰ = ContinuousPolynomial{0}(r)

x = axes(C,1)
D = C⁰ \ (Derivative(x) * C¹)

# D[1,1] should be -5 not -0.5
```

I think `M = BlockVcat(Hcat(Ones{T}(N) / 2, -Ones{T}(N) / 2), H)` in line 241 of [PiecewiseOrthogonalPolynomials.jl](https://github.com/JuliaApproximation/PiecewiseOrthogonalPolynomials.jl/blob/main/src/PiecewiseOrthogonalPolynomials.jl) should be

`M = BlockVcat(Hcat(Ones{T}(N) * (N-1), -Ones{T}(N) * (N-1)), H)`

**Comment by ioannisPApapadopoulos** [comment]
happy to make a PR if you agree

**Comment by dlfivefifty** [comment]
I have no clue but it should be easy to write unit tests so make your changes with unit tests that fail under the current implementation and I'll merge
